### ISSUE TITLE
 Fails!  × compact(): Undefined variable: assign

### ISSUE THREAD

**Issue by calmills** [ladybirdweb/faveo-helpdesk#1293]
- Faveo Version : 1.10.4
- PHP version :7.3
- Database Driver & Version : MYSQL 
- Server specification : Windows Server 2016

#### Description:
When trying to add a new agent this error is generated;

 Fails!  × compact(): Undefined variable: assign 

There are also Reference errors relating to DKEDITOR

#### Steps To Reproduce:

Go to admin panel and add a new agent

#### Downloaded from
- [x ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by shredstick** [comment]
I have the exact same Setup with exact same Issue.

**Comment by mverma16** [comment]
The issue is due to the missing parameter alert thrown by `compact()` in PHP version 7.3. [Read more here](https://hackernoon.com/deprecations-and-changes-for-php-7-3-avoid-errors-7a5c4dbeaa8b#ff55).

We have not tested or updated the system to work with PHP7.3, but are soon going to start working on it and we will release an update by the end of this month.

**Comment by ravikant14** [comment]
Kindly help getting same error message. 

How can i fixed this issue or i can install any specific version of PHP

**Comment by PeopleInside** [comment]
I have the same issue

**Comment by PeopleInside** [comment]
I'M sorry to see PHP 7.3 is not yet supported, this cause so many issues not only the reported error here.
In just few month PHP 7.2 will be deprecated (end of life).
Seems the open source Faveo doesn't have a commit since last year 2019.

Sorry to see this because the software was look good. I cannot use as I have PHP 7.3 and cannot downgrade.
Sorry to see no patch, no solution.

**Comment by ImShobhitPundir** [comment]
i have one solution for that issue you can add these lines under AgentController in create function:
$assign= NULL;
$agents=NULL;

**Comment by JedMeister** [comment]
Is support for PHP7.3 for Faveo "Community" planned?

Or is Faveo "Community" basically abandonware? (I note that beyond the recent sec update, the previous release was Dec 2019).

**Comment by LifeSteala** [comment]
> i have one solution for that issue you can add these lines under AgentController in create function:
> $assign= NULL;
> $agents=NULL;

This worked!
But I then downgraded PHP to 7.2 from 7.3.
