### ISSUE TITLE
Composer install warnings

### ISSUE THREAD

**Issue by acs-ferreira** [ladybirdweb/faveo-helpdesk#211]
Ubuntu 14.04
PHP 7.0
````
Package illuminate/html is abandoned, you should avoid using it. Use laravelcollective/html instead.
Package chumper/datatable is abandoned, you should avoid using it. Use OpenSkill/Datatable instead.
Warning: Ambiguous class resolution, "App\Http\Controllers\Agent\helpdesk\UserController" was found in both "/public/app/Http/Controllers/Agent/helpdesk/UserController.php" and "/public/app/Http/Controllers/Auth/UserController.php", the first will be used.
````

**Comment by mverma16** [comment]
@acs-ferreira Thanks for notifying these warnings.

- We are using [chumper datatable](https://github.com/Chumper/Datatable) for rendering various datatables in the system. Chumper has stopped updation in that repository for laravel version > 5.0 and he is now developing new datatable repository called Open Skill. FAVEO is currently using Larave 5.2 and we've customized chumper datatable package  in a way that it will work flawlessly in FAVEO.  We are currently exploring different datatable packages to use in FAVEO and we'll try to update the datatable package as we shift FAVEO to Laravel 5.3. Same goes for the "illuminate/html" package. 

- Both "UserControllers" have different methods and different functionalities. But We'll try to rename one controller so that this ambiguity can be avoided.

We are open to suggestions. If you have any better idea we can work on that together or if you are a developer please send us PR after altering the code.

**Comment by mverma16** [comment]
Closing the issue till @acs-ferreira replies back.
