### ISSUE TITLE
Delete User

### ISSUE THREAD

**Issue by supportreq** [ladybirdweb/faveo-helpdesk#306]
There is no way to delete an existing user.. please advice..

**Comment by jgrabitzky** [comment]
User or agent ?
i have the same problem to delete an existent agent. No Delete Button.

In the file /resources/views/themees/default1/admin/helpdesk/agent/agents/index.blade.php
on line 106 i change from:

 {{-- {!! Form::button(' <i class="fa fa-trash" style="color:black;"> </i> '  . Lang::get('lang.delete') ,['type' => 'submit', 'class'=> 'btn btn-warning btn-xs btn-flat','onclick'=>'return confirm("Are you sure?")']) !!} --}}

to

 {!! Form::button(' <i class="fa fa-trash" style="color:black;"> </i> '  . Lang::get('lang.delete') ,['type' => 'submit', 'class'=> 'btn btn-warning btn-xs btn-flat','onclick'=>'return confirm("Are you sure?")']) !!}

(delete  {{-- and  --}} on first and last line )

and the delete button is showing.

**Comment by mverma16** [comment]
In the latest version [v.1.0.8.0](https://github.com/ladybirdweb/faveo-helpdesk/) you can delete users and change their role as well.

All you need it to open user directory form dashboard
![1](https://cloud.githubusercontent.com/assets/10759797/20167627/b0700738-a742-11e6-8bc5-51033996e996.png)

You'll see the list of all the users(including agents)
![2](https://cloud.githubusercontent.com/assets/10759797/20167652/cd0ee490-a742-11e6-84ad-925b7991754f.png)

Click on view profile and it will open profile of a user
![3](https://cloud.githubusercontent.com/assets/10759797/20167671/e8d4dc48-a742-11e6-925d-135b1105982f.png)

You can click on delete to delete the user.

> Note: You need to select option to what to do with the tickets created(by clients)/assigned(to agents) by the user you want to delete.

If you are using an older version of Faveo

- Please download the latest code from [here](https://github.com/ladybirdweb/faveo-helpdesk/)
- And upgrade your system following this [upgrade article](https://github.com/ladybirdweb/faveo-helpdesk/wiki/How-to-update-v1.0.7.9-to-v1.0.8.0)

**Comment by kevinleberge** [comment]
jgrabitzky is correct - I deleted agent from Users page and it shows on Admin side as inactive.  I reactivate user on admin side and it doesn't show on the user side anymore.  

No way to delete users from admin side, and it doesn't delete properly.

**Comment by mverma16** [comment]
Here's the catch in deleting users, as the application is intended for providing hassle free customer support solution to business owners, sometime it may contain some important information added by users. 
Example: An agent can add replies on ticket. Later if you delete the agent those replies must be archived under the name of that agent, which can be used for future references.

Currently we do not delete the agent from database, we just deactivate the user's account. So that all replies from the agents can be retained in future.

We are open for suggestions to handle the scenarios where user has been deleted and business owner wants to get information about the replies/activities done by the agent on tickets.

**Comment by kevinleberge** [comment]
Force all user actions to be transferred to another user.  If stats are an issue then a hidden user named "deleted user" can be used.
