### ISSUE TITLE
imap mail issue

### ISSUE THREAD

**Issue by aslamsd** [ladybirdweb/faveo-helpdesk#3552]
- Faveo Version : #.#.#
- PHP version :
- Database Driver & Version :
- Server specification :

#### Steps To Reproduce:

Kerberos error: No kerberos credentials available (try running kinit) for domain

![image](https://user-images.githubusercontent.com/67919086/86796705-eabf3300-c07f-11ea-9cd3-7070142aa44d.png)

#### Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by aslamsd** [comment]
Kindly help

**Comment by PeopleInside** [comment]
Hi @aslamsd ,
how someone can help you if you doesn't use the mask to fill an issue?

You never specified PHP version, Faveo version, ecc.
You did not provide steps to reproduce.

I tested the community version recently in PHP 7.2 and I configured email without issue so maybe you may try to configure a different email address but also specify more details here by compiling what is required for open an issue here.

I think I will be not able to help you but I write because I see you have not provided much informations.

**Comment by aslamsd** [comment]
Please find below details. Thank you

**PHP Version => 7.4.7**

System => Linux lamp 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64

Server version: **Apache/2.4.38 (Debian)**
Server built:   2019-10-15T19:53:42
Server's Module Magic Number: 20120211:84
Server loaded:  APR 1.6.5, APR-UTIL 1.6.1
Compiled using: APR 1.6.5, APR-UTIL 1.6.1

**Faveo Version Community 1.10.7**

**Comment by PeopleInside** [comment]
Faveo doesn't support PHP 7.4 or PHP 7.3
Have you tried to disable the certificate verification?

**Comment by bhanu2217** [comment]
New version of Faveo v2.0.1 supports PHP 8.1 You can test and see if the issue still exists in this version
