### ISSUE TITLE
Opening "Create Ticket" and Sending New Ticket took a long time

### ISSUE THREAD

**Issue by equa24** [ladybirdweb/faveo-helpdesk#408]
When I clicked "Create Ticket" to create a new ticket, it took me almost 20 seconds to load the whole page. Also, when sending the ticket or replying ticket, it also took 20 seconds to successfully send it.

I'm using the app on my shared hosting account on A2-Hosting (Turbo Package). I don't know much about their hardware specs, but I know we're using 3GB physical memory and 8GB virtual memory, all 0% usage. I used PHP 5.6.

As for my ISP, well, my office had 2 Mb/s of downstream speed.

**Comment by SarfrazS** [comment]
It depends on the queue service you are using for sending mails. 
You can check it in Admin settings>Emails> Queues

If it's `sync` then it is sending emails to the client and admin/agent users at the time of ticket creation which is a time consuming process.
You can use `database` instead of `sync` so that all email sending jobs will be scheduled in database and will run in background resulting in making your system faster. 
But for that you need to use single cron command 
>/usr/bin/php-cli -q  /path_to_faveo_root_directory/support/code/artisan schedule:run >> /dev/null 2>&1

which will run on your server every minute. 
Also we've noticed that this single cron command does not perform well on shared servers.

**Comment by raisiqueira** [comment]
When creating a new ticket as a regular user, the system redirects and returns the Excess Redirection error. (URL / dashboard)
