### ISSUE TITLE
Multi user (customer) collaboration

### ISSUE THREAD

**Issue by neven-vujasinovic** [ladybirdweb/faveo-helpdesk#418]
Hello Faveo team!

As far as I've seen it is possible for more agents (developers) to collaborate on a ticket.

But I haven't seen if the same is possible for multiple users (customers). If users are added as collaborators they will get email notifications on emails but will not be able to set ticket status or reply to ticket and really collaborate. I see these collaborators more like watchers than real collaborators.

There is an option to transfer ownership of ticket from one user to another but what if more than one user needs to see the status of ticket and also be able to write replies at the same time or change status. For example, one user discovers a problem and opens a ticket but another user or group of users (another department) needs to test it and change the status. Or at least is it possible for a user to see ticket history of another owner (but not in emails)?

I think it would be good if there were some mechanism of allowing some additional users to also collaborate on a ticket. Because the user that creates a ticket is not always the one that will change status or reply to a ticket. Also, more users would want to see the status of another user's ticket without asking him directly or looking through emails, for example when original owner gets sick or away for any reason. 

Is this kind of functionality maybe in plans or is it already available and I missed it? What are your thoughts about this?

Thank you,
Neven

**Comment by mverma16** [comment]
Hello

Thanks for such a great suggestion. This will definitely help end users to check tickets as a team/organization. 
Our current collaborator option just loops the added person in conversation but does not allow him/her to check ticket status or change the status.
Client users can be grouped in an organization but this also does not give them access of the tickets created by other users in their organization.
We have it in a plan to make organizational access over tickets. So that managers of an organization can see tickets of other users in their organization.
