### ISSUE TITLE
POP3 Incoming email results in duplicate tickets.  Disabling inbound does not stop the issue.

### ISSUE THREAD

**Issue by liamkennedy** [ladybirdweb/faveo-helpdesk#490]
- Faveo Version : 1.9.6
- PHP version : 5.6
- Database Driver & Version : MySQL
- Server specification : Debian/Apache

#### Description:
I configured the email settings to connect with a POP3 email account for our helpdesk and started testing by submitting two help requests to the email account

I configured the scheduler to check email every 5 minutes.  Those two emails came in as tickets (GOOD).  

However now every 5 minutes it would duplicate each ticket.   

I then disabled the Inbound option (unchecked the option in the email settings) and saved the settings again.  However the scheduler was still connecting to the POP3 server and bringing in the duplicate tickets every 5 minutes.  

My fix to that was to change to IMAP (which the account does not support).  Now I can see in the logs my system is still trying to connect to the inbound mailbox - but failing of course.  At least I'm not getting duplicate tickets.,  

So... this is TWO issues really.   

#### Steps To Reproduce:

As above.

#### Downloaded from
- [x ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by derek68** [comment]
Hi All

I have the same issue, with version Service Desk Community 17cf90b.  But im using Imap.  So ive had to disable to the user account.

Can someone please help.

Regards

**Comment by liamkennedy** [comment]
Sad to see it's also happening with IMAP. but.. at least that saves me the hassle of trying that out.  

WIthout this feature working it makes the helpdesk practically useless for my needs.

**Comment by derek68** [comment]
I fully understand, I hope it is fixed quickly.  Are you running Faveo on windows or linux?

**Comment by vijaysebastian** [comment]
@liamkennedy thank you for notifying this. 
Faveo read mail with a search - 'with in -1 day and now','unseen mails'.
POP3 can read the mail but it can't mark 'seen' after fetch but imap.

We will try to find a solution soon.

**Comment by mathieu-aubin** [comment]
True, POP protocol relies on the client to take care of its messages... but the server is helping us a bit:

Looking a bit closer at the rfc for [_**P**ost **O**ffice **P**rotocol_](https://www.ietf.org/rfc/rfc1939.txt) you can see a command called **UIDL** which you can use to mark (in your local storage, not on the server) what message you have already downloaded/seen.

@vijaysebastian, try this on a working POP3 server:

```
openssl s_client -crlf -connect SERVER_HOST:110 -starttls pop3
```

Once connected to the POP server, input the CAPA command (which stands for capabilities) and check the ouput... sample would be like so:

```
+OK Dovecot ready.
CAPA
+OK
CAPA
TOP
UIDL
RESP-CODES
PIPELINING
AUTH-RESP-CODE
USER
SASL PLAIN LOGIN
.
```

If you actually login with a user and a pass, you can send the UIDL command to the server and it'll return a list of the current messages in the mailbox and a **U**nique **ID** **L**isting for each of them. 

Here's an asciicast that potentially describes the thing better than i can speak it now:

[![asciicast](https://asciinema.org/a/1dbbnvc7p3cfy10zqq97i4995.png)](https://asciinema.org/a/1dbbnvc7p3cfy10zqq97i4995)

**Comment by derek68** [comment]
Hi All

Is there any news on fixing this error?

Regards

**Comment by retorquere** [comment]
Same problem here, with IMAP. Can't the reader just delete the mail after it's done? Or move it to a different folder?

**Comment by retorquere** [comment]
Why not set the `SEEN` flag after fetch? Wouldn't that fix things? The mail scanner only looks for `UNSEEN` mails. Something like [this](https://stackoverflow.com/questions/6765736/set-an-email-as-seen-on-imap-server#6768497)?

**Comment by derek68** [comment]
So has anyone got a fix?

**Comment by liamkennedy** [comment]
I decided to try IMAP.. and configured my mail account hosting to a version that supported IMAP.  This feature NOW works just fine.  Only one ticket gets created for each incoming mail to the account.  I'm not sure what may be happening to others who have posted that IMAP didn't work.. but for whatever reason it's not failing for me.

**Comment by feligato** [comment]
I have the same issue, with POP3 or IMAP, every message that arrives to the inbox keeps gettin duplicated. The only way to solve it is to delete the message manually from the inbox, not the ideal solution.

For me this a deal breaker

![image](https://user-images.githubusercontent.com/18687345/34048887-22b1a482-e194-11e7-9ac9-fe52950168e5.png)

**Comment by superkekko** [comment]
I've the same error too.

**Comment by ozancanb** [comment]
Yes, At the and i will fix the codes on the /opt/faveo/faveo-helpdesk/app/Http/Controllers/Agent/helpdesk/**MailController.php** after that when get message add the faveo than delete from server, so duplicated mails fixed for me :) 👍

**Comment by mverma16** [comment]
@feligato can you share more details so we can check why are you still facing the issue with IMAP? Though fetching mails via IMAP should not fetch the duplicate tickets but we will try to replicate the same. Also we are working on fixing the same with POP3.

**Comment by ozancanb** [comment]
My Mail server does not support IMAP, so I must use POP3 first I was add username to Email Controller then for the duplicate mail While fetching mail from POP3 I was setflag to deleted after everything finished expunge mail.

` $message->setFlag('deleted');  `
` $server->expunge(); `

**Comment by mathieu-aubin** [comment]
I'm still wondering why [this method of using _UIDL_](https://github.com/ladybirdweb/faveo-helpdesk/issues/490#issuecomment-309210239) for _POP_ hasn't even been considered/replied-to/tried **_a full year_** after having been posted.

Its clearly an easy to implement solution that only requires the addition of either a temporary file (hidden) or a database table in which to mark the messages _UIDL_ that have already been seen.

Marking a _UIDL_ as seen is a way to at least temporary fix the problem until a better solution can be cooked up. That is **_if_** the protocol allows for a better solution.

I have no idea about windows but a good place to store such temporary files on linux could be in /var/cache/xxxxxxx - assuming it is installed by an admin

**Comment by in4tekdev** [comment]
i have the same problem with POP3 and can't understand why this topic-issue is closed.
Where is the solution?

**Comment by mathieu-aubin** [comment]
@in4tekdev ... check my previous last message... it is clear that my explanation and recommendation to do more than just read my comment, rather TRY and experience, while soaking in some valuable experience, has been disregarded.

**Comment by in4tekdev** [comment]
@mathieu-aubin 
i've read your message, as indeed i've read all the others, as i usually do: i always read the entire thread, in order to understand better the steps that led to a certain result.
I also assure you that i'm not the kind of guy that goes straight to the ready-made solution, i try on my own, i experiment as far as my skills and knowledge allow me.
I don't find a solution to this issue, anyway it's not marked as fixed, am i right? Yours is a workaround as yourself say : 
_> Marking a UIDL as seen is a way to at least temporary fix the problem until a better solution can be cooked up_

You seems frustrated and probably you have open discussion with someone on this project, i don't know and i don't care, but this does not entitle you to answer unkind to other people's comments. 
I am grateful to you all for the job you done here, I respect you and other users so please do the same.
Thank you

**Comment by mathieu-aubin** [comment]
Believe me, i am not frustrated... However, i have given ALOT of very valuable time and ressources to both faveo and it's parent company. Enough to be mentionned on the website at some point, which was kinda funny!! I have no idea who you are tho, i dont recall meeting you or maybe you changed your handle for some mysterious reason, its not important.

No, i am not frustrated but... dissapointed i guess. And yes, i believe my message wasn't the most respectful but it was not towards any individuals on a personnal basis but just with regards to the way things used to be, in general, from what i remember.

And yes, what i suggested is something temporary but i must say something... suggestions are almost never suggested to be used as-is but to help kick-start a thought process around -most likely- a new or different way of doing/thinking things that have never been explored, thougnt of or, even simpler, were compmetely unknown. This usually requires some research and commitment which more often than not, result in a different solution that has higher projects environ. requirements awereness and consideration. When i suggested this, i was well aware that the protocol was not fully understood and that comes from personnal chat and interactions with people and not a deduction or something similar. I was, at some point, teaching - **on a daily basis and a personnal level** - to team members about protocols they were using and many other of linux's technological things they had to understand clearly so to properly interact with. This generally (hopefully) goes a long way towards better quality of developped products while being on the same level as the competition, if not (again hopefully) on a higher one.

Hey, i was even offered shares in the company...

All in all, my commeny was meant to shake things up a bit, stir some sludge in hopes that what i have experienced during my time and inspite many efforts by myself and others,that the way of doing has changed and positively. As you said yourself... or from what i understand when reading your comment...

It makes no sense to close an issue that is NOT resolved or to close an issue WITHOUT a mention to anything ressembling a solution or even just a reason to close the issue, per example to open another one, more specofic or for any other reason. I does not feel right nor is it a good practice to close issues without any kind of related materials or reasons/explications. After all, Git and issue reporting system is a tool to help progress tracking while being a historical reference to what has been tried, its results and effects.

I dont see where i was unkind to any other's comments and again, all i was saying referred to how faveo development had been done before and i hope (by stirring stuff) that it had changed (making people react usually calls for thoses types of changes).

If you took whatever i said personnally then... i'm sorry because nothing was aimed at you. Why would i "attack" someone with which i agree and has basically just said... 'not resolved, still problems, show me the sokutiin'. Its too bad you think of me this way and that for some reason, you felt targeted by mycomment.

**Comment by mathieu-aubin** [comment]
should have made it clearer like...



> ..... while soaking in some valuable experience, has been disregarded ** by developpers **.

again, this... to me anyways, clearly does NOT point at you ...
> I have done A TON to help regarding this project, mostly behind the scenes stuff as server/computer assets and networking solutions goes. Most of the recommendations and/or warnings, more often than not, were completely disregarded or, even worst i think, were approached without any understanding of the issue i was referring to and swiftly navigating/pretending to understand even just the tiniest bit

**Comment by mathieu-aubin** [comment]
deleted my comments to minimize polution.
