### ISSUE TITLE
Demo Login does not work

### ISSUE THREAD

**Issue by wowcut** [ladybirdweb/faveo-helpdesk#500]
The demo logins proveded [here](https://www.faveohelpdesk.com/online-demo/) do not work. The demo site shows up but after a login attempt there is an http error 500.

Please monitor your demo site for errors, as it is a very important entry point for potential new users - a broken demo site might give very wrong impressions about your quality standards.

**Comment by mverma16** [comment]
@wowcut, Thanks for informing about the problem with our demo site.
We agree that this kind of issues are unacceptable and may result us in loosing our prospective users. We are checking the possible reasons for occurrence of the issue.

Here are few possible reasons(I can think of)
* Our demo has no access restriction, may be somebody has  tweaked some settings from admin panel.(Ex: Somebody has deleted all language package available for translation)
* Demo site data gets refreshed after every half an hour, may be some thing went wrong while refreshing database.

We've reset the demo and it is working now. 
Once again we thank you for notifying the issue, we'll try to make the demo more secure and interactive so that other users don't face the same problem and they can explore all functionalities of the system.

**Comment by mathieu-aubin** [comment]
close this
