### ISSUE TITLE
lfm.php prevents successful composer update

### ISSUE THREAD

**Issue by ajanes3** [ladybirdweb/faveo-helpdesk#52]
If you run composer update, it will error out.

```
 Error Output: PHP Catchable fatal error:  Argument 2 passed to Iluminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in ..\faveo-helpdesk\vendor\laravel\framework\src\Illuminate\Routing\RoutingServiceProvider.php on line 56 and defined in ..\faveo-helpdesk\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php on line 95
```

This is due to the assigned images_url parameter in config/lfm.php line 12:

`'images_url' => url('photos').'/'`

I changed this to:

`'images_url' => '/photos/'`

Composer update now works when I make this change.

**Comment by vijaysebastian** [comment]
@ajanes3 this will work on normal case but the problem is, if someone not using public in their url, file manager will not work. 

So here I am going to describe how to solve this issue.

1. You can comment or delete this line from config\lfm.php `'images_url'         => url('photos').'/',`
2. In your App\Providers\ConfigServiceProvider.php add this code to your register function
`config([
                'lfm.images_url' => url('photos').'/',
        ]);`
3. Now your register method in ConfigServiceProvider.php seems like this.

`public function register() {
        config([
                'lfm.images_url' => url('photos').'/',
        ]);
    }`

**Comment by vijaysebastian** [comment]
We will fix this issue in next release.
