### ISSUE TITLE
Site broken links, no information on how to install.

### ISSUE THREAD

**Issue by StrangerPings** [ladybirdweb/faveo-helpdesk#538]
http://www.ladybirdweb.com/support/ 404s

 😖

**Comment by StrangerPings** [comment]
![screen shot 2017-10-18 at 11 26 50](https://user-images.githubusercontent.com/22084825/31713786-594fe58c-b3f7-11e7-8e84-3e7fb4c957cc.png)

Also this

**Comment by mverma16** [comment]
@StrangerPings  We regret that you faced issues on our site.  :disappointed:
Thanks for reporting the problem with our site. We recently updated the system to latest PRO version of the application.
There were some configurations issues in system settings due to which KB page was was inactive and extra fields were added in registration form. We've updated the settings and KB page is active now.

Please follow [this link](https://www.ladybirdweb.com/support/category-list/installation-and-upgrade-guide) to browse articles for installation of the system. 

I am closing the issue now, feel free to reopen if you still face the issues on our site.
