### ISSUE TITLE
Invalid email address error on signup

### ISSUE THREAD

**Issue by genez** [ladybirdweb/faveo-helpdesk#539]
- Faveo Version : Ladybirdweb's own online instance
- PHP version : 
- Database Driver & Version :
- Server specification :

#### Description:
I tried to register myself (create account) but email validation keeps telling me my address is invalid.
my email is in the form `name.surname@my-domain.it` 

removing the dash works, but my domain has the dash and is perfectly legit

#### Steps To Reproduce:
Go to https://www.ladybirdweb.com/support/auth/register

**Comment by mverma16** [comment]
@genez thanks for notifying the issue we had in custom forms. The issue you mentioned was occurring due to improper JavaScript regex for checking email address in we have updated our system with Faveo Pro v1.9.16. Now you'll be able to register with your email address and submit your ticket request. 

For complete updates and features of Faveo Pro v1.9.16, please follow [this link](stablehelpdesk.faveohelpdesk.co.in) to check them in action on our  live demo.
