### ISSUE TITLE
How change "SUPPORT CENTER"

### ISSUE THREAD

**Issue by francesco1119** [ladybirdweb/faveo-helpdesk#54]
I'm editing the theme, how to change "SUPPORT CENTER" in the main page?
How change the favicon.ico?

**Comment by francesco1119** [comment]
Favicon.ico changed by replacing the madia image but where can I find the file to edit the homepage?

**Comment by bhanu2217** [comment]
Support Centre(logo) can be changed from Admin Panel >> Settings >> Company and Admin Panel >> Settings >> System Incase company name is not set the title will show otherwise company name will show


**To change client side theme colours:** https://github.com/ladybirdweb/faveo-helpdesk/wiki/Change-client-side-theme-color

**Comment by francesco1119** [comment]
I have changed the name but nothing changes

**Comment by SarfrazS** [comment]
Please see below the attachments
![capture1](https://cloud.githubusercontent.com/assets/18435376/15178865/005a9c78-1796-11e6-9f17-9f08752b816f.PNG)
![capture2](https://cloud.githubusercontent.com/assets/18435376/15178864/005a14ba-1796-11e6-8b98-88b5b4096968.PNG)
