### ISSUE TITLE
[Security] XSS in dompdf/dompdf/www/demo.php

### ISSUE THREAD

**Issue by seongil-wi** [ladybirdweb/faveo-helpdesk#5423]
- Faveo Version : v1.11.0 and below versions
- PHP version : 7.1.33
- Database Driver & Version : MySQL 5.5.62
- Server specification : Apache 2.4.29, Turn on the AcceptPathInfo in apache2.conf

#### Description:

Reflected Cross-Site Scripting (XSS) may allow an attacker to execute JavaScript code in the context of the victim’s browser. This may lead to unauthorized actions being performed, unauthorized access to data, stealing of session information, denial of service, etc. An attacker needs to coerce a user into visiting a link with the XSS payload to be properly exploited against a victim.

#### Steps To Reproduce:

1. Go to the http://[localhost]/faveo-helpdesk/vendor/dompdf/dompdf/www/index.php
2. Login
3. Go tot the page with the following link: http://[localhost]/faveo-helpdesk/vendor/dompdf/dompdf/www/demo.php/%22%3E%3Cscript%3Ealert(1)%3C/script%3E
4. Boom!

**Where the Issue Occurred**
The code below displays the user-controlled input `PHP_SELF` in `demo.php` without sufficient sanitization:
https://github.com/ladybirdweb/faveo-helpdesk/blob/4752081caff32ce8c378fd97ba5525aabd94c8f7/vendor/dompdf/dompdf/www/demo.php#L35

**Note**
Although the dompdf page is accessible from localhost, it can be attacked if the localhost user clicks on the aforementioned link.

#### Downloaded from
- [*] master-branch
 
- [*] release-tag: v1.11.0

**Comment by Noor-mommadhi** [comment]
@seongil-wi please use the updated version to avoid the issue

**Comment by SarfrazS** [comment]
> @seongil-wi please use the updated version v2.0.1 to avoid the issue

@Noor-mommadhi  Did you cross-check in our latest version? if yes Please can you help to sabari.

**Comment by Sabaric12** [comment]
Now I have cross checked with the older version and current version that demo.php and index.php file is not there Now I added that in the latest version and I tried to login it is going to 404 page that issue is not occuring here
![Screenshot from 2023-05-25 11-52-56](https://github.com/ladybirdweb/faveo-helpdesk/assets/118339159/7de4fdc8-9b93-42b1-8b0a-82c0329c11ed)

![Screenshot from 2023-05-25 11-52-21](https://github.com/ladybirdweb/faveo-helpdesk/assets/118339159/0d9d7cf1-9233-4d77-8750-7900544e2a90)
![Screenshot from 2023-05-25 11-52-11](https://github.com/ladybirdweb/faveo-helpdesk/assets/118339159/81692a01-5345-4b7b-be81-8a57bbb2aaa3)
