### ISSUE TITLE
Too few Arguments

### ISSUE THREAD

**Issue by CokkocZateki** [ladybirdweb/faveo-helpdesk#558]
- Faveo Version : v1.9.6
- PHP version : PHP 7.1.12-2
- Database Driver & Version : Mysql 
- Server specification : Ubuntu 14.04

#### Description:
After installing Faveo-Helpdesk i navigate to the address i set. page displays 

```
FatalThrowableError in Manager.php line 77:
Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected
```

#### Downloaded from
- [x] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
HI @CokkocZateki, as we have not tested the system with PHP 7 or greater version I'd suggest you to downgrade your PHP version to v5.6.* which is the best fit for Faveo v1.9.6. 
Please revert if downgrading PHP version does not solve the issue. Due to some other requirements we were not able to actively maintain the repository. But we are soon going to update the repository and release new version of Faveo with the latest [Laravel version](https://github.com/laravel/laravel)
