### ISSUE TITLE
Not importing e-mails

### ISSUE THREAD

**Issue by Bananenbaas** [ladybirdweb/faveo-helpdesk#59]
Hi Guys, 

Since I've added a workflow the system stops importing e-mails. I cannot find where it's going wrong... 
I've deleted the workflow and re-added all the e-mail addresses. 

When I manually go to the url /readmails it gives me the message Mailbox is empty while it's not empty... None of the in total 5 e-mail addresses I've added. There is nothing in the apache error logs or no errors in the others error logs.

**Comment by SarfrazS** [comment]
Hi Bananenbaas, 

In the first scenario when you created the workflow, you might have choose an action to reject the emails. And when you remove the workflow the tickets went as more than one day ago older due to which the system didn’t fetch the email and the current system IMAP settings don't receive tickets for more than one day ago.
In our next release we have added pop settings which will read all the unpopped emails that never got popped with this feature you can fetch all your tickets more than one day ago while you can keep using IMAP to fix for one day.
Do let us know for more issue.
