### ISSUE TITLE
Ticket and Article Knowledge Base not showing

### ISSUE THREAD

**Issue by syaiful1254** [ladybirdweb/faveo-helpdesk#703]
- Faveo Version : 1.9.6
- PHP version : 5.6
- Database Driver & Version : mysql 5.6
- Server specification : shared hosting

#### Steps To Reproduce: First login admin panel -> then i click inbox -> just show a loading
And in the knowledge base -> when i click tool menu -> knowledge base -> all article -> just showing
. But if i just add article, the article can show in homepage client. 

Inbox Ticket
![inbox](https://user-images.githubusercontent.com/26919316/46642946-fa0c0680-cba3-11e8-96c9-a9cbd6734730.JPG)

Knowledge Base
![knowledge base](https://user-images.githubusercontent.com/26919316/46642947-fa0c0680-cba3-11e8-99bc-7f783b40edcc.JPG)

#### Downloaded from
- [ Yes ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by mverma16** [comment]
Enable debugging mode and navigate to networks in developer console of your browser and restrict it to show XHR requests by clicking XHR in filters. Please share the API response to troubleshoot the issue.

**Comment by syaiful1254** [comment]
we not have API Response like your request

![image](https://user-images.githubusercontent.com/26919316/46786502-43ed1c00-cd5f-11e8-9cf2-e32c4660715e.png)

**Comment by mverma16** [comment]
To debug the issue first enable debugging mode. To enable debugging mode go to admin panel > errors and debugging > enable debugging mode.

Then share the error in API response by clicking on the request shown in the image below.

![46787047-df32c100-cd60-11e8-9354-27fe370112c3 png 1883x863](https://user-images.githubusercontent.com/10759797/46852954-5c6e3c80-ce1a-11e8-8670-d77961df794b.png)

**Comment by syaiful1254** [comment]
APIkey = siGzDeEApmmbmpmSxKJSSFgwskEGXiQe

**Comment by FrancescoSteno** [comment]
In Admin Panel, Tickets -> statuses -> Edit details , update and change only the Name field.

	• _method: PATCH
	• _token: BQntKqrAgHfC8h8IwS84krR1181B3gMzwgankiWp
	• name: Chiuso
	• sort: 3
	• icon_class: fa fa-edit
	• state: closed
	• delete: no
	• email_user: yes




in the methodeditStatuses($id, StatusRequest $request), I see that the form send the correct information:

array:8 [

  "_method" => "PATCH"
 "_token" => "BQntKqrAgHfC8h8IwS84krR1181B3gMzwgankiWp"
  "name" => "Chiuso
""sort" => "3""
icon_class" => "fa fa-edit"
  "state" => "closed"
  "delete" => "no"  "
email_user" => “yes”
]

the variable $statuss contains the correct value, but the only value that was modified in the table Ticket_Status is the name …
I tried to modify the Ticket_Status Model (that extends the BaseModel), adding in the $fillable array by adding email_user (that was missed) but the issue is still there.
There is something wrong in the in the BaseModel -> setAttributes method ?

Best regards 

Francesco Steno

My configuration is PHP 7.1.21 (cli) (built: Oct  4 2018 21:12:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans

**Comment by syaiful1254** [comment]
thanks for fix this issue
